#!/usr/bin/env bash

apt-get update
apt-get install -qyy nginx

cd /opt/webogram
wget https://web.telegram.org/webogram.appcache

chown -R www-data:www-data /opt/webogram

apt-get clean -qq
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
