#!/usr/bin/env bash

apt-get update
apt-get install -qyy nginx

wget -O /opt/webogram/webogram.appcache https://web.telegram.org/webogram.appcache
wget -O /opt/webogram/js/locales/en-us.json https://github.com/TelegramCN/TelegramCN.github.io/raw/master/transifex/Web.json

chown -R www-data:www-data /opt/webogram

apt-get clean -qq
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
