#!/usr/bin/env bash

apt-get update
apt-get install -qyy git build-essential zip
WEBOGRAM_SRC=/usr/local/src/webogram
mkdir -p $WEBOGRAM_SRC
git clone https://github.com/zhukov/webogram.git $WEBOGRAM_SRC
cd $WEBOGRAM_SRC
git checkout -qf 61401c8a14d643a472ec20baddea8480e9cede2e
npm install -g -q gulp
npm install -q
version=0.5.5 make
mv $WEBOGRAM_SRC/dist_package /opt/webogram
rm -rf $WEBOGRAM_SRC
apt-get clean -qq
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
